apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
  namespace: miniflask
  labels:
    app: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login-container
        image: mannanrawat/flasklogin-service:latest  # Replace with your actual image
        ports:
        - containerPort: 5000
#        readinessProbe:  # Optional health check for /health endpoint
#          httpGet:
#            path: /health
#            port: 5000
#          initialDelaySeconds: 5
#          periodSeconds: 10
#          timeoutSeconds: 2
#          failureThreshold: 3
